# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loadingscreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SplashScreen(object):
    def setupUi(self, SplashScreen):
        SplashScreen.setObjectName("SplashScreen")
        SplashScreen.resize(680, 400)
        self.centralwidget = QtWidgets.QWidget(SplashScreen)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.dropShadowFrame = QtWidgets.QFrame(self.centralwidget)
        self.dropShadowFrame.setStyleSheet("QFrame{\n"
"\n"
"background-color: rgb(0, 51, 0);\n"
"color: rgb(0,255,0);\n"
"border-radius: 10px;\n"
"\n"
"}")
        self.dropShadowFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.dropShadowFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.dropShadowFrame.setObjectName("dropShadowFrame")
        self.label = QtWidgets.QLabel(self.dropShadowFrame)
        self.label.setGeometry(QtCore.QRect(150, 40, 211, 181))
        self.label.setStyleSheet("background-image: url(:/newPrefix/—Pngtree—red and black logo_5517319.png);")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/newPrefix/—Pngtree—red and black logo_5517319.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.dropShadowFrame)
        self.label_2.setGeometry(QtCore.QRect(310, 110, 191, 51))
        self.label_2.setStyleSheet("font: 87 36pt \"Arial Black\";\n"
"color: rgb(207, 207, 207);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.dropShadowFrame)
        self.label_3.setGeometry(QtCore.QRect(300, 160, 231, 31))
        self.label_3.setStyleSheet("font: 25 20pt \"Bahnschrift Light\";\n"
"color: rgb(0, 170, 0);")
        self.label_3.setObjectName("label_3")
        self.progressBar = QtWidgets.QProgressBar(self.dropShadowFrame)
        self.progressBar.setGeometry(QtCore.QRect(130, 260, 461, 23))
        self.progressBar.setStyleSheet("QProgressBar{\n"
"\n"
"    background-color: rgb(105, 165, 96);\n"
"    color: rgb(48, 173, 10);\n"
"    border-style: none;\n"
"    border-radius: 10px;\n"
"    text-align: center;\n"
"\n"
"}\n"
"\n"
"QProgressBar::chunk{\n"
"    \n"
"    border-radius:10px;\n"
"    \n"
"    background-color: qlineargradient(spread:pad, x1:0.293806, y1:0.466, x2:0.995025, y2:0.523, stop:0 rgba(59, 119, 0, 255), stop:1 rgba(245, 0, 0, 255));\n"
"\n"
"}")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.label_4 = QtWidgets.QLabel(self.dropShadowFrame)
        self.label_4.setGeometry(QtCore.QRect(310, 290, 81, 31))
        self.label_4.setStyleSheet("font: 25 12pt \"Bahnschrift Light\";\n"
"color: rgb(0, 170, 0);")
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.dropShadowFrame)
        SplashScreen.setCentralWidget(self.centralwidget)

        self.retranslateUi(SplashScreen)
        QtCore.QMetaObject.connectSlotsByName(SplashScreen)

    def retranslateUi(self, SplashScreen):
        _translate = QtCore.QCoreApplication.translate
        SplashScreen.setWindowTitle(_translate("SplashScreen", "MainWindow"))
        self.label_2.setText(_translate("SplashScreen", "AYB"))
        self.label_3.setText(_translate("SplashScreen", "Rescue System"))
        self.label_4.setText(_translate("SplashScreen", "loading..."))
import mainLogo_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SplashScreen = QtWidgets.QMainWindow()
    ui = Ui_SplashScreen()
    ui.setupUi(SplashScreen)
    SplashScreen.show()
    sys.exit(app.exec_())
