# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SignInScreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1081, 768)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("QFrame{\n"
"\n"
"background-color: rgb(0, 51, 0);\n"
"color: rgb(0,255,0);\n"
"\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setGeometry(QtCore.QRect(170, 120, 751, 481))
        self.frame_3.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.284, y1:0.318182, x2:1, y2:1, stop:0 rgba(170, 0, 0, 255), stop:1 rgba(0, 85, 0, 255));")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.frame_2 = QtWidgets.QFrame(self.frame_3)
        self.frame_2.setGeometry(QtCore.QRect(10, 10, 731, 461))
        self.frame_2.setStyleSheet("background-color: rgb(0, 51, 0);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.userTxt = QtWidgets.QLineEdit(self.frame_2)
        self.userTxt.setGeometry(QtCore.QRect(150, 130, 421, 41))
        self.userTxt.setStyleSheet("QLineEdit{\n"
"\n"
"border: 2px solid  rgb(67, 203, 203);\n"
"border-radius: 15px;\n"
"color: #FFF;\n"
"    \n"
"    background-color:rgb(0, 61, 0);\n"
"\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"\n"
"border: 2px solid rgb(0, 189, 0);\n"
"\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"\n"
"border: 2px solid rgb(0, 255, 0);\n"
"\n"
"}")
        self.userTxt.setObjectName("userTxt")
        self.passwordTxt = QtWidgets.QLineEdit(self.frame_2)
        self.passwordTxt.setGeometry(QtCore.QRect(150, 280, 421, 41))
        self.passwordTxt.setStyleSheet("QLineEdit{\n"
"\n"
"border: 2px solid  rgb(67, 203, 203);\n"
"border-radius: 15px;\n"
"color: #FFF;\n"
"    \n"
"    background-color:rgb(0, 61, 0);\n"
"\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"\n"
"border: 2px solid rgb(0, 189, 0);\n"
"\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"\n"
"border: 2px solid rgb(0, 255, 0);\n"
"\n"
"}")
        self.passwordTxt.setObjectName("passwordTxt")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setGeometry(QtCore.QRect(150, 80, 141, 31))
        self.label_5.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";\n"
"color: rgb(202, 202, 202);")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setGeometry(QtCore.QRect(150, 230, 141, 31))
        self.label_6.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";\n"
"color: rgb(202, 202, 202);")
        self.label_6.setObjectName("label_6")
        self.WrongUsername = QtWidgets.QLabel(self.frame_2)
        self.WrongUsername.setGeometry(QtCore.QRect(160, 190, 401, 16))
        self.WrongUsername.setStyleSheet("color: rgb(213, 213, 0);")
        self.WrongUsername.setText("")
        self.WrongUsername.setObjectName("WrongUsername")
        self.WrongPassword = QtWidgets.QLabel(self.frame_2)
        self.WrongPassword.setGeometry(QtCore.QRect(150, 340, 421, 16))
        self.WrongPassword.setStyleSheet("color: rgb(213, 213, 0);")
        self.WrongPassword.setText("")
        self.WrongPassword.setObjectName("WrongPassword")
        self.showCheck = QtWidgets.QCheckBox(self.frame_2)
        self.showCheck.setGeometry(QtCore.QRect(180, 380, 231, 20))
        self.showCheck.setStyleSheet("font: 12pt \"MS Sans Serif\";\n"
"color: rgb(255, 255, 0);")
        self.showCheck.setObjectName("showCheck")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(480, 40, 161, 51))
        self.label.setStyleSheet("font: 75 22pt \"Verdana\";")
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(190, 80, 191, 51))
        self.label_4.setStyleSheet("font: 87 36pt \"Arial Black\";\n"
"color: rgb(207, 207, 207);")
        self.label_4.setObjectName("label_4")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(20, 10, 211, 181))
        self.label_2.setStyleSheet("background-image: url(:/newPrefix/—Pngtree—red and black logo_5517319.png);")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/newPrefix/—Pngtree—red and black logo_5517319.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(170, 130, 231, 31))
        self.label_3.setStyleSheet("font: 25 20pt \"Bahnschrift Light\";\n"
"color: rgb(0, 170, 0);")
        self.label_3.setObjectName("label_3")
        self.loginBtn = QtWidgets.QPushButton(self.frame)
        self.loginBtn.setGeometry(QtCore.QRect(550, 630, 261, 51))
        self.loginBtn.setStyleSheet("QPushButton{\n"
"\n"
"border-radius: 25px;\n"
"    background-color: rgb(0, 127, 127);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 63 12pt \"Yu Gothic UI Semibold\";\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    background-color: rgb(0, 88, 88);\n"
"\n"
"}\n"
"")
        self.loginBtn.setObjectName("loginBtn")
        self.exitBtn = QtWidgets.QPushButton(self.frame)
        self.exitBtn.setGeometry(QtCore.QRect(270, 630, 261, 51))
        self.exitBtn.setStyleSheet("QPushButton{\n"
"\n"
"border-radius: 25px;\n"
"    background-color: rgb(227, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 63 12pt \"Yu Gothic UI Semibold\";\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    background-color:rgb(138, 0, 0);\n"
"\n"
"}\n"
"")
        self.exitBtn.setObjectName("exitBtn")
        self.frame_3.raise_()
        self.label.raise_()
        self.loginBtn.raise_()
        self.exitBtn.raise_()
        self.label_2.raise_()
        self.label_4.raise_()
        self.label_3.raise_()
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_5.setText(_translate("MainWindow", "Username "))
        self.label_6.setText(_translate("MainWindow", "Password "))
        self.showCheck.setText(_translate("MainWindow", "Show Password"))
        self.label.setText(_translate("MainWindow", "Sign In"))
        self.label_4.setText(_translate("MainWindow", "AYB"))
        self.label_3.setText(_translate("MainWindow", "Rescue System"))
        self.loginBtn.setText(_translate("MainWindow", "Login"))
        self.exitBtn.setText(_translate("MainWindow", "Exit"))
import mainLogo_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
